/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";

type GLTFResult = GLTF & {
    nodes: {
        Cube019: THREE.Mesh;
        Cube019_1: THREE.Mesh;
        Cube019_2: THREE.Mesh;
    };
    materials: {
        StoneDark: THREE.MeshStandardMaterial;
        ["White.029"]: THREE.MeshStandardMaterial;
        ["Metal.076"]: THREE.MeshStandardMaterial;
    };
};

export default function BookModel(props: JSX.IntrinsicElements["group"]) {
    const group = useRef<THREE.Group>();
    const { nodes, materials } = useGLTF(
        "https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/book/model.gltf"
    ) as GLTFResult;
    return (
        <group ref={group} {...props} dispose={null}>
            <group rotation={[Math.PI / 2, 0, 0]}>
                <mesh
                    geometry={nodes.Cube019.geometry}
                    material={materials.StoneDark}
                />
                <mesh
                    geometry={nodes.Cube019_1.geometry}
                    material={materials["White.029"]}
                />
                <mesh
                    geometry={nodes.Cube019_2.geometry}
                    material={materials["Metal.076"]}
                />
            </group>
        </group>
    );
}

useGLTF.preload(
    "https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/book/model.gltf"
);
